logo_path = r"\\mercury\Producción\Minutas Produccion\Program Files\logo.png"
BASE_EVIDENCIAS = r"\\mercury\Producción\Minutas Produccion\Program Files\evidencias_acuerdos"
ruta_image=r"\\mercury\Producción\Minutas Produccion\Program Files\img.jpg"
DB_PATH=r"\\mercury\Producción\Minutas Produccion\Program Files\minutas.db"
MASTER=r"\\mercury\Producción\Minutas Produccion\Program Files\dbs_rutas\master.db"